// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLIahNMouKkT7waPt9TmssIPNArHoR1nA',
    appId: '1:460968421715:web:655da90977036e5c5e19a6',
    messagingSenderId: '460968421715',
    projectId: 'test-flutter-206ee',
    authDomain: 'test-flutter-206ee.firebaseapp.com',
    storageBucket: 'test-flutter-206ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5xYO0jrbDEmouIkp7FSxV_zdAbwn-srQ',
    appId: '1:460968421715:android:592c54dfc7cf8f3b5e19a6',
    messagingSenderId: '460968421715',
    projectId: 'test-flutter-206ee',
    storageBucket: 'test-flutter-206ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_ROGfA8B_o8ebkliUuBJUZ-08V3kzQE',
    appId: '1:460968421715:ios:6984b9cf0ee71e625e19a6',
    messagingSenderId: '460968421715',
    projectId: 'test-flutter-206ee',
    storageBucket: 'test-flutter-206ee.firebasestorage.app',
    iosBundleId: 'com.petrahtimirov.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_ROGfA8B_o8ebkliUuBJUZ-08V3kzQE',
    appId: '1:460968421715:ios:65c40c995f4b65ba5e19a6',
    messagingSenderId: '460968421715',
    projectId: 'test-flutter-206ee',
    storageBucket: 'test-flutter-206ee.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLIahNMouKkT7waPt9TmssIPNArHoR1nA',
    appId: '1:460968421715:web:9574aac31f554f575e19a6',
    messagingSenderId: '460968421715',
    projectId: 'test-flutter-206ee',
    authDomain: 'test-flutter-206ee.firebaseapp.com',
    storageBucket: 'test-flutter-206ee.firebasestorage.app',
  );
}
